# SPDX-FileCopyrightText: 2019 Contributors to the P4 Project
#
# SPDX-License-Identifier: Apache-2.0

BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = pod-topo/topology.json
DEFAULT_PROG = basic.p4

include ../../utils/Makefile
